#!/bin/sh
#
# ~/.xprofile

# BLACK SCREEN
hsetroot -solid "#000000" &

export SSH_ASKPASS=ssh-askpass
export DOTFILES="$HOME/.DOTFILES"
export $(dbus-launch)

# DAEMONS ----------------------------------------------------------------------
#mpd --no-daemon &
nm-applet &
#clipit --daemon &


# AUTOSTART --------------------------------------------------------------------
file=$DOTFILES/$1/autostart

if [[ -f $file ]]; then
    . "$file"
else
    notify-send 'Welcome!' "Not found file autostart '($file)'" --icon=dialog-warning
fi
unset file
