#!/bin/sh
#
# ~/.xprofile

export DOTFILES=$HOME/.DOTFILES

# DAEMONS ----------------------------------------------------------------------
# mpd --no-daemon &
# hsetroot -solid "#000000" &
# thunar --daemon &
nm-applet &
#clipit --daemon &


# AUTOSTART --------------------------------------------------------------------
autostart() {
    file=$DOTFILES/$1/autostart
    if [[ -f $file ]]; then
        sh $file
    else
        notify-send 'Bienvenido!' 'No se encontró el archivo autostart "($file)"' --icon=dialog-warning
    fi
}
autostart $1 &
