#!/bin/sh
#
# ~/.xprofile

export DOTFILES="$HOME/.DOTFILES"

# DAEMONS ----------------------------------------------------------------------
mpd --no-daemon &
hsetroot -solid "#000000" &
nm-applet &
#clipit --daemon &


# AUTOSTART --------------------------------------------------------------------
file=$DOTFILES/$1/autostart

if [[ -f $file ]]; then
    . "$file"
else
    notify-send 'Bienvenido!' "No se encontró el archivo autostart '($file)'" --icon=dialog-warning
fi
unset file
