#! /bin/sh

# DAEMONS ======================================================================
urxvtd &
synapse --startup &
compton --config $DIR_DOTFILES/compton.conf -b &
xscreensaver &
xss-lock -- xscreensaver-command -lock &

# FIX 
# pkill notify-osd

# APLICACIONES =================================================================
(sleep 10 && pidgin) &
(sleep 10 && liferea) &
