#! /bin/sh

#DAEMONS -----------------------------------------------------------------------
feh --bg-fill $DOTFILES/i3/background --no-fehbg &
compton --config $DOTFILES/compton.conf -b &
synapse --startup &
redshift -l -16.3988:-71.5369 &


#APPLICATIONS ------------------------------------------------------------------
#(sleep 15 && pidgin) &
