#! /bin/sh

#DAEMONS -----------------------------------------------------------------------
hsetroot -solid '#505050' -fill $DOTFILES/i3/background &
compton --config $DOTFILES/compton.conf -b &
redshift -l -16.3988:-71.5369 &
albert &


#APPLICATIONS ------------------------------------------------------------------
#(sleep 15 && pidgin) &
