#! /bin/sh 

SCRIPTS=$DOTFILES/scripts 
CONKY=$DOTFILES/i3/conky
TMP=/tmp 

GREEN="#aaf096"
YELLOW="#f0dc64"
ORANGE="#ff9933"
RED="#ff3333"

ICON_CPU=""
ICON_MEM=""
ICON_UP=""
ICON_DOWN=""
ICON_TEMP=""
ICON_MAIL=""
ICON_PACMAN=""
ICON_CALENDAR=""
ICON_CLOCK=""
ICON_VOLUME=""
ICON_BATTERY=""
ICON_MUSIC=""

IFS=";"

main() {
    # GMAIL
    PACMAN

    echo '{ "version": 1 }'
    echo '['
    echo '[],'
    info
}

info() {
    conky -c $CONKY | while read -r; do 
        LINE='{"full_text":""}'

        read -ra DATA <<< "$REPLY"

        # float to int 
        DATA[1]=$(echo ${DATA[1]} | sed 's/,.*$//')  # down speed
        DATA[3]=$(echo ${DATA[3]} | sed 's/,.*$//')  # up speed

        music_mpd ${DATA[10]}
        temperature ${DATA[0]}
        downspeed ${DATA[1]} ${DATA[2]}
        upspeed ${DATA[3]} ${DATA[4]}
        memory ${DATA[5]} ${DATA[6]}
        cpu ${DATA[7]}
        battery ${DATA[8]}
        volume ${DATA[9]} # system and mpd

        icon $ICON_CALENDAR "#a0a0a0"
        datetime '%A, %d de %B'
        icon $ICON_CLOCK "#eeeeee"
        datetime '%I:%M %P'

        # mails
        packages

        line '' ', "separator_block_width":10'

        echo -e "[$LINE],"
    done
}

temperature() {
    icon $ICON_TEMP "#ffff00"

    if [[ $1 -lt 45 ]]; then
        COLOR=$GREEN
    elif [[ $1 -lt 50 ]]; then
        COLOR=$YELLOW
    elif [[ $1 -lt 55 ]]; then
        COLOR=$ORANGE
    else
        COLOR=$RED
    fi

    line "$1°C"
}

downspeed() {
    icon $ICON_DOWN "#06b800"

    if [[ $1 -lt 100 ]]; then
        COLOR=$GREEN
    elif [[ $1 -lt 300 ]]; then
        COLOR="#68b1e8"
    elif [[ $1 -lt 700 ]]; then
        COLOR="#db70b8"
    elif [[ $1 -lt 1000 ]]; then
        COLOR="#9470db"
    else
        COLOR=$RED
    fi

    line "$2"
}

upspeed() {
    icon $ICON_UP "#53b1ff"

    if [[ $1 -lt 15 ]]; then
        COLOR=$GREEN
    elif [[ $1 -lt 35 ]]; then
        COLOR="#9470db"
    else
        COLOR=$RED
    fi

    line "$2"
}

memory() {
    icon $ICON_MEM "#777777"

    if [[ $1 -lt 30 ]]; then
        COLOR=$GREEN
    elif [[ $1 -lt 60 ]]; then
        COLOR=$YELLOW
    elif [[ $1 -lt 85 ]]; then
        COLOR=$ORANGE
    else
        COLOR=$RED
    fi

    line "$2"
}

cpu() {
    icon $ICON_CPU "#ccbb00"

    if [[ $1 -lt 25 ]]; then
        COLOR=$GREEN
    elif [[ $1 -lt 50 ]]; then
        COLOR=$YELLOW
    elif [[ $1 -lt 75 ]]; then
        COLOR=$ORANGE
    else
        COLOR=$RED
    fi

    line "$1%"
}

battery() {
    icon $ICON_BATTERY "#333333"

    if [[ $1 -gt 50 ]]; then
        COLOR=$GREEN
    elif [[ $1 -gt 25 ]]; then
        COLOR=$YELLOW
    elif [[ $1 -gt 10 ]]; then
        COLOR=$ORANGE
    else
        COLOR=$RED
    fi

    line "$1%"
}

datetime() {
    FORMAT=$1
    line "$(date +"$FORMAT")"
}

volume() {
    icon $ICON_VOLUME "#00cccc"
    line "$(amixer sget Master,0 | egrep -m 1 -o '([0-9]+%)')" ', "separator_block_width":5'
    COLOR="#a80066"
    line "$1%"
}

music_mpd() {
    icon $ICON_MUSIC "#aa0096"
    COLOR="#a80066"
    if [[ $1 == "OFF" ]]; then
        COLOR=$RED
    fi
    line "$1" ', "min_width":350'
}

mails() {
    n="$(cat $TMP_MAIL)"
    if [[ $n -le 0 ]]; then
        return
    fi

    icon $ICON_MAIL $ORANGE
    line "$n"
}

packages() {
    n="$(cat $TMP_PACMAN)"
    if [[ $n -le 0 ]]; then
        return
    fi

    icon $ICON_PACMAN "#ffe200"
    line "$n"
}

GMAIL() {
    TMP_MAIL="$TMP/.gmail-inbox"
    while : ; do 
        MAILS="$($SCRIPTS/gmail)"
        echo "$MAILS" > $TMP_MAIL
        sleep 10
    done &
}

PACMAN() {
    TMP_PACMAN="$TMP/.pacman-packages"
    while : ; do 
        pacman -Qu | wc -l > $TMP_PACMAN
        sleep 500
    done &
}

icon() {
    COLOR=$2
    line $1 ', "separator_block_width":5'
}

line() {
    LINE=$LINE',{"full_text":"'$1'", "color":"'$COLOR'", "separator":false, "separator_block_width":15 '$2'}'
}


main
