#!/bin/bash
#
# Mostrar captura de pantalla al bloquear
#
file1=$(mktemp --tmpdir i3lock-XXXXXXXXXX.png)
file2=$(mktemp --tmpdir i3lock-XXXXXXXXXX.png)

scrot "$file1"
convert "$file1" -blur 0x3 "$file2"
i3lock -n -i "$file2"
rm "$file1" "$file2"
