#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)


if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi


numlockx &
mpd --no-daemon &
xrdb -merge ~/.Xresources &
# hsetroot -solid "#000000" &
feh --bg-fill ~/Imágenes/shana.png

.aek6/scripts/key

nvidia-settings -a InitialPixmapPlacement=2

exec i3
