#!/usr/bin/sh
texto=`cat ~/.fehbg`
texto=${texto:15}
ruta='/home/maigo/Imágenes/Fondos/'${texto//\'/}
# propiedades=
i=0
for p in `identify $ruta`
do
    i=$[i+1]
    if [ $i = 3 ]; then
        size=$p
    fi
done
w=$(expr "$size" : '\(.*x\)')
h=$(expr "$size" : '.*\(x.*\)')
w=${w//x/}
h=${h//x/}
# h=$[h / 5]
base=225
borde=8
temp=$[h / base]
h=$base
# w=$[w / 5]
w=$[w / temp]
size=$w'x'$h
sizeb=$[w + borde]'x'$[h + borde]
# ubicacion
x=$[1570 - w]
y=$[720 - h]
xb=$[x - borde / 2]
yb=$[y - borde / 2]
echo "\${image ~/.aek6/scripts/img/fondo2-conky.png -p $xb,$yb -s $sizeb}\${image $ruta -p $x,$y -s $size}\\"
