#!/usr/bin/perl

# $namebg = `cat  ~/.fehbg`;
# @data = split(" ", $namebg);
# $path = substr($data[2], 1, length($data[2]) - 2);
$path = `~/.aek6/scripts/image-random`;

$size = `identify $path`;
@data = split(" ", $size);
$size = $data[2];
$w = substr($size, 0, index($size, "x"));
$h = substr($size, index($size, "x") + 1);

$new_h = 225;       # Nueva altura de la imágen.
$min_w = 350;       # acho minimo de la imágen.
$scale = $h / $new_h;
if ($w / $scale < $min_w) {
    $scale = $w / $min_w;
    $w = $min_w;
    $h /= $scale;
    $h = sprintf("%.0f", $h)
} else {
    $w /= $scale;
    $h = $new_h;
    $w = sprintf("%.0f", $w)
}

$border = 4;        # Borde de la imagen.
# $x = 1570 - $w;     # Punto (x, y) de la pantalla donde iniciará
# $y = 790 - $h;      # la esquina inferior derecha de la imágen.
$x = 0;
$y = 0;

$text = "echo \\\\\\\${image ~/.aek6/scripts/img/fondo2-conky.png -p " . ($x - $border) . "," . ($y - $border) . " -s " . ($w + $border * 2) . "x" . ($h + $border * 2) . "}\\\\\\\${image $path -p $x,$y -s $w" . "x" . "$h}\\";
`echo $text > ~/.imgbgconky`;
`chmod +x ~/.imgbgconky`;
