#!/bin/sh

# arrays de windows managers
# agregar si hay mas opciones
wms=(i3 awesome compiz)
xinitrc=(~/.aek6/i3/xinitrc ~/.aek6/awesome/xinitrc ~/.aek6/compiz/xinitrc)


# colores
NORMAL='\033[m'
BLUE='\033[1;34m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
RED='\033[0;31m'
GREEN='\033[0;32m'
FUCCIA='\033[1;35m'
WHITE='\033[1;37m'


ascii_img(){
    echo -e '\e[H\e[2J' 
    echo -e '                                                            \e[1;30m| \e[34m\\s \\r' 
    echo -e '       \e[36;1m/\\\\                      \e[37m||     \e[36m| |                   \e[30m|' 
    echo -e '      \e[36m/  \\\\                     \e[37m||     \e[36m|     _               \e[30m| \e[32m\\t' 
    echo -e '     \e[1;36m/ \e[0;36m.. \e[1m\\\\   \e[37m//==\\\\\\\\ ||/= /==\\\\ ||/=\\\\  \e[36m| | |/ \\\\ |  | \\\\ /     \e[30m| \e[32m\\d' 
    echo -e '    \e[0;36m/ .  . \\\\  \e[37m||  || ||   |    ||  || \e[36m| | |  | |  |  X      \e[1;30m|' 
    echo -e '   \e[0;36m/  .  .  \\\\ \e[37m\\\\\\\\==/| ||   \\\\==/ ||  || \e[36m| | |  | \\\\_/| / \\\\     \e[1;30m| \e[31m\\U' 
    echo -e '  \e[0;36m/ ..    .. \\\\   \e[0;37mA simple, lightweight linux distribution.  \e[1;30m|' 
    echo -e ' \e[0;36m/_\x27        `_\\\\                                             \e[1;30m| \e[35m\\l \e[0mon \e[1;33m\\n' 
    echo -e ' \e[0m' 
    echo -e '' 
}

show_menu(){
    i=1
    lon=0
    opciones="| "
    borde="+"
    for wm in ${wms[*]}; do
        opciones="$opciones$YELLOW$i) $GREEN$wm  $RED| "
        i=$[i + 1]
        lon=$[${#wm} + ${#i}]
        for (( j = 0; j < lon + 4; j++ )); do
            borde="$borde-"
        done
        borde="$borde+"
    done
    lon=$i

    # lon=0
    # for x in ${xinitrc[*]}; do
    #     lon=$[lon + 1]
    # done

    echo -e "Elige el WM(Gestor de ventanas) que quieres iniciar"
    echo -e $RED$borde
    echo -e $opciones
    echo -e $RED$borde
    echo -e "\n${YELLOW}Dame el numero de tu opción: "
    read opt

    # if [ $opt -gt 0 ]; then
    #     if [ $opt -le $lon ]; then
    #         echo ${xinitrc[$opt - 1]}
    #     fi
    # fi
    # if ((opt > 0 && opt < lon))
    # then
    #      echo ${xinitrc[$opt - 1]}
    # fi

    i=1
    for x in ${xinitrc[*]}; do
        if [ $opt == $i ]; then
             echo ${xinitrc[$opt - 1]}
            ln -fs ${xinitrc[$opt - 1]} ~/.xinitrc;
            exit 0;
        fi
        i=$[i + 1]
    done
}

iniciar(){
    clear
    ascii_img
    show_menu
    echo -e "\n${WHITE}Elige Correctamente una de las opciones dadas o te botare del sistema...";
    echo -e "Continuar... ${NORMAL}";
    read enter
    iniciar
}

iniciar
