#!/bin/sh

wms=(i3 compiz herbstluftwm awesome bspwm openbox)

# colores
NORMAL='\033[m'
BLUE='\033[1;34m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
RED='\033[0;31m'
GREEN='\033[0;32m'
FUCCIA='\033[1;35m'
WHITE='\033[1;37m'


ascii_img(){
    echo -e '\e[H\e[2J' 
    echo -e '                                                            \e[1;30m| \e[34m\\s \\r' 
    echo -e '       \e[36;1m/\\\\                      \e[37m||     \e[36m| |                   \e[30m|' 
    echo -e '      \e[36m/  \\\\                     \e[37m||     \e[36m|     _               \e[30m| \e[32m\\t' 
    echo -e '     \e[1;36m/ \e[0;36m.. \e[1m\\\\   \e[37m//==\\\\\\\\ ||/= /==\\\\ ||/=\\\\  \e[36m| | |/ \\\\ |  | \\\\ /     \e[30m| \e[32m\\d' 
    echo -e '    \e[0;36m/ .  . \\\\  \e[37m||  || ||   |    ||  || \e[36m| | |  | |  |  X      \e[1;30m|' 
    echo -e '   \e[0;36m/  .  .  \\\\ \e[37m\\\\\\\\==/| ||   \\\\==/ ||  || \e[36m| | |  | \\\\_/| / \\\\     \e[1;30m| \e[31m\\U' 
    echo -e '  \e[0;36m/ ..    .. \\\\   \e[0;37mA simple, lightweight linux distribution.  \e[1;30m|' 
    echo -e ' \e[0;36m/_\x27        `_\\\\                                             \e[1;30m| \e[35m\\l \e[0mon \e[1;33m\\n' 
    echo -e ' \e[0m' 
    echo -e '' 
}

show_menu(){
    i=1
    lon=0
    opciones="| "
    borde="+"
    for wm in ${wms[*]}; do
        opciones="$opciones$YELLOW$i) $GREEN$wm  $RED| "
        i=$[i + 1]
        lon=$[${#wm} + ${#i}]
        for (( j = 0; j < lon + 4; j++ )); do
            borde="$borde-"
        done
        borde="$borde+"
    done
    lon=$i

    echo -e "\n${YELLOW}Elige el WM(Gestor de ventanas) que quieres iniciar:"
    echo -e $RED$borde
    echo -e $opciones
    echo -e $RED$borde
    echo -e "\n${YELLOW}Dame el numero de tu opción: ${NORMAL}"
    read opt

    i=1
    for x in ${wms[*]}; do
        if [ $opt == $i ]; then
            wm=$x
            if [[ $wm == "compiz" ]]; then
                wm="compiz cpp"
            fi

            echo $wm > ~/.xinitwm
            exit 0;
        fi
        i=$[i + 1]
    done
}

iniciar(){
    # ascii_img
    show_menu
    echo -e "\n${WHITE}Elige Correctamente una de las opciones dadas o te botare del sistema...";
    echo -e "Continuar... ${NORMAL}";
    read enter
    clear
    iniciar
}

iniciar
