#!/bin/sh

# WINDOWS MANAGERS
WMS=$(ls /usr/share/xsessions | sed 's/\.desktop$//')

# COLORS
NORMAL='\033[m'
BLUE='\033[1;34m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
RED='\033[0;31m'
GREEN='\033[0;32m'
FUCCIA='\033[1;35m'
WHITE='\033[1;37m'


ascii_img() {
    echo -e '\e[H\e[2J' 
    echo -e '                                                            \e[1;30m| \e[34m\\s \\r' 
    echo -e '       \e[36;1m/\\\\                      \e[37m||     \e[36m| |                   \e[30m|' 
    echo -e '      \e[36m/  \\\\                     \e[37m||     \e[36m|     _               \e[30m| \e[32m\\t' 
    echo -e '     \e[1;36m/ \e[0;36m.. \e[1m\\\\   \e[37m//==\\\\\\\\ ||/= /==\\\\ ||/=\\\\  \e[36m| | |/ \\\\ |  | \\\\ /     \e[30m| \e[32m\\d' 
    echo -e '    \e[0;36m/ .  . \\\\  \e[37m||  || ||   |    ||  || \e[36m| | |  | |  |  X      \e[1;30m|' 
    echo -e '   \e[0;36m/  .  .  \\\\ \e[37m\\\\\\\\==/| ||   \\\\==/ ||  || \e[36m| | |  | \\\\_/| / \\\\     \e[1;30m| \e[31m\\U' 
    echo -e '  \e[0;36m/ ..    .. \\\\   \e[0;37mA simple, lightweight linux distribution.  \e[1;30m|' 
    echo -e ' \e[0;36m/_\x27        `_\\\\                                             \e[1;30m| \e[35m\\l \e[0mon \e[1;33m\\n' 
    echo -e ' \e[0m' 
    echo -e '' 
}

menu() {
    i=1
    lon=0
    options="| "
    border="+"

    for wm in ${WMS[*]}; do
        options="$options$YELLOW$i. $GREEN$wm  $RED| "
        i=$[i + 1]
        lon=$[${#wm} + ${#i}]
        for (( j = 0; j < lon + 4; j++ )); do
            border="$border-"
        done
        border="$border+"
    done
    lon=$i

    echo -e "\n${YELLOW}Choose window manager to init:"
    echo -e $RED$border
    echo -e $options
    echo -e $RED$border
    echo -e "\n${YELLOW}Number option: ${NORMAL}"
    read opt

    i=1
    for wm in ${WMS[*]}; do
        if [ $opt == $i ]; then
            echo $wm
            exit 0;
        fi
        i=$[i + 1]
    done
}

__init__() {
    ascii_img
    menu
    echo -e "\n${WHITE}Option invalid!. (Ctrl+C continue in console)";
    echo -e "Continue... ${NORMAL}";
    read enter
    clear
    __init__
}

__init__
