#! /usr/bin/sh

. $DIR_DOTFILES/awesome/COLORS.lua

count=$($DIR_DOTFILES/scripts/gmail)

if [[ $count -lt 0 ]]; then
    count="."
    color="#000000"
elif [[ $count -eq 0 ]]; then
    color=$GREEN
elif [[ $count -le 2 ]]; then
    color=$YELLOW
else
    color=$ORANGE
fi

echo -e "$1:set_markup('<span foreground=\"$color\">$count</span>')" | awesome-client
