#! /bin/sh

#DAEMONS
# wicd-client --tray &
mpd --no-daemon &
nm-applet &
# thunar --daemon &
clipit --daemon &
# synapse --startup &
pa-applet &

#ESCRITORIO
# (sleep 7 && tint2 -c ~/.aek6/compiz/tint2/tray.tint2rc) &
# (sleep 7 && tint2 -c ~/.aek6/compiz/tint2/reloj.tint2rc) &
# (sleep 7 && tint2 -c ~/.aek6/compiz/tint2/izquierda.tint2rc) &
# (sleep 7 && tint2 -c ~/.aek6/compiz/tint2/derecha.tint2rc) &

# (sleep 5 && tint2 -c ~/.aek6/compiz/tint2/dock.tint2rc) &
$HOME/.aek6/compiz/conky/conky.sh &
$HOME/.aek6/compiz/conky/conky-mpd.sh &
# covergloobus &
(sleep 5 && plank) &
xfce4-panel &

#APLICACIONES
(sleep 15 && pidgin) &

